### ISSUE TITLE
"progn: Symbol’s value as variable is void: cps-state-terminal-1176" after M-x eval-buffer

### ISSUE THREAD

**Issue by stevenfontanella** [skeeto/emacs-aio#18]
Minimal example:
```elisp
(require 'aio)

(setq lexical-binding t)

(aio-defun test ()
  1)

(aio-wait-for (test))
```

Strangely this program works when I eval everything one-by-one using C-x C-e. I'm wondering if there's something wrong with using eval-buffer with this library. Thanks for the help.

Emacs version:
```
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-12-02
```

**Comment by skeeto** [comment]
The problem is that setq lexical-binding isn't a reliable way to enable 
lexical scope. You must use the file-local-variable form in the header.
