### ISSUE TITLE
edebug support?

### ISSUE THREAD

**Issue by Silex** [skeeto/emacs-aio#24]
Hello,

Thanks for this package, it makes emacs async sane.

Is there a way to use edebug tho? All my attempts seems to fail, even when explicitely writing `(edebug)` in my forms.

**Comment by mooseyboots** [comment]
@Silex i'm also unable to use edebug with aio, know what you did? evaluating my aio-defuns also returns t, not sure if related...

**Comment by Silex** [comment]
@mooseyboots no I don't know what I did, but in any case it's normal they return `t` I think because of how aio works.
