### ISSUE TITLE
Can `emacs-aio` support Emacs 25?

### ISSUE THREAD

**Issue by kiennq** [skeeto/emacs-aio#7]
From the README it seems that `emacs-aio` is using Emacs 25 generator, but the requirement for it is Emacs 26.
Can `emacs-aio` works with Emacs 25?

**Comment by skeeto** [comment]
As mentioned in the README, aio uses the "record" built-in function 
which is Emacs 26. It's not fundamentally required like generators, but 
it's generally nice to build upon a recent baseline. Emacs 26 is already 
nearly two years old, and the minimum version will remain Emacs 26 for a 
long time.

**Comment by kiennq** [comment]
Thanks
